### ISSUE TITLE
Add method to preemptively open payment channel

### ISSUE THREAD

**Issue by emschwartz** [machinomy/machinomy#123]
For my use case I'd like to ensure that a payment channel is opened to the receiver when the sender starts up (and I can get the receiver's address before I actually want to load content from them). It would be nice if there were an easy way to open a payment channel without actually paying the receiver.

**Comment by ukstv** [comment]
There is a (hacky) way for doing this:
1. Instantiate Machinomy object, setting `minimumChannelAmount` to an expected channel amount (https://github.com/machinomy/machinomy/blob/master/index.ts#L48 and https://github.com/machinomy/machinomy/blob/master/index.ts#L109).
2. Do `machinomy.buy` with `price` set to 0. (https://github.com/machinomy/machinomy/blob/master/index.ts#L21)

Would that fit your case?

**Comment by emschwartz** [comment]
Yup, that worked. Thanks!

**Comment by ukstv** [comment]
Yay! Cool.
