### ISSUE TITLE
Switch to Rinkeby?

### ISSUE THREAD

**Issue by michielbdejong** [machinomy/machinomy#160]
The genesis file mentioned in the [instructions for connecting to Ropsten](https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/) is no longer available for download. Maybe it's time to switch to Rinkeby instead in the readme instructions? https://github.com/machinomy/machinomy/commit/b47ca9d9594de4c23c10613546a693b0797f4046 suggests it should work?

**Comment by ukstv** [comment]
@michielbdejong You do not have to download genesis block or anything to use Ropsten. If you use any recent client, `geth --testnet` joins Ropsten.

**Comment by michielbdejong** [comment]
It's now on Rinkeby if you use latest master from github, thanks!
