### ISSUE TITLE
Should `acceptPayment` throw an error if the payment is for less than a previous payment?

### ISSUE THREAD

**Issue by kincaidoneil** [machinomy/machinomy#224]
My understanding is that if the payment is otherwise valid, it persists it to the db, and *only when claiming the channel*, the receiver checks for the payment with the maximum value.

For our use case, we really need the ability to know what the largest payment/best claim is so we can reject payments for which the value is less than a previous payment.

Is there a way to do that using the current API? Or should acceptPayment throw an error if it's not the greatest payment?

**Comment by ARyaskov** [comment]
Hi, @kincaidoneil ! Good suggestion. We plan to realize this check after we'll finish ERC20 support.

**Comment by ARyaskov** [comment]
Merged. Thank you very much for contributing!
