### ISSUE TITLE
sqlite3 dependency install issue

### ISSUE THREAD

**Issue by masterial** [machinomy/machinomy#249]
Can't install machinomy dependencies on macOs. Thanks!

<img width="1680" alt="screen shot 2018-09-04 at 4 18 42 pm" src="https://user-images.githubusercontent.com/11956729/45062588-6f912e00-b05e-11e8-9743-8beb9faf9572.png">

**Comment by ARyaskov** [comment]
I think you need try to use Node.js v9 instead of v10.
